#!/bin/sh

# Copy files
cp -r ./opt/muse-hub /opt
cp ./usr/bin/muse-hub /usr/bin/muse-hub
cp ./usr/bin/muse-hub-service /usr/bin/muse-hub-service
cp ./usr/lib/systemd/system/muse-hub.service /usr/lib/systemd/system/muse-hub.service
cp ./usr/share/applications/muse-hub.desktop /usr/share/applications/muse-hub.desktop
cp ./usr/share/icons/hicolor/48x48/apps/muse-hub.png /usr/share/icons/hicolor/48x48/apps/muse-hub.png
cp ./usr/share/icons/hicolor/64x64/apps/muse-hub.png /usr/share/icons/hicolor/64x64/apps/muse-hub.png
cp ./usr/share/icons/hicolor/128x128/apps/muse-hub.png /usr/share/icons/hicolor/128x128/apps/muse-hub.png
cp ./usr/share/icons/hicolor/256x256/apps/muse-hub.png /usr/share/icons/hicolor/256x256/apps/muse-hub.png

# Start services
systemctl daemon-reload
systemctl enable --now muse-hub.service

exit 0
