#!/bin/sh

rm -rf /srv/muse-hub/logs
rm -rf /tmp/muse-hub
rm -rf "$HOME/.muse-hub"

# Kill the Muse Hub Client application
if pgrep -f Muse.Client.Linux; then killall Muse.Client.Linux; fi

# Disable the Muse Hub Helper Service
systemctl --no-reload disable --now muse-hub.service

rm -rf /opt/muse-hub
rm -rf /usr/bin/muse-hub
rm -rf /usr/lib/systemd/system/muse-hub.service
rm -rf /usr/share/applications/muse-hub.desktop
rm -rf /usr/share/icons/hicolor/48x48/apps/muse-hub.png
rm -rf /usr/share/icons/hicolor/64x64/apps/muse-hub.png
rm -rf /usr/share/icons/hicolor/128x128/apps/muse-hub.png
rm -rf /usr/share/icons/hicolor/256x256/apps/muse-hub.png

exit 0
